apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fortune
  labels:
    app: fortune
spec:
  template:
    metadata:
      labels:
        app: fortune
        tier: web
    spec:
      containers:
      - name: fortune
        image: windmill.build/millie/fortune
        command: ["/go/bin/fortune"]
        env:
        - name: TEMPLATE_DIR
          value: "/go/src/github.com/dbentley/fortune/templates"
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: fortune
  labels:
    app: fortune
spec:
  type: LoadBalancer
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: fortune
  selector:
    app: fortune