apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vigoda
  labels:
    app: vigoda
spec:
  template:
    metadata:
      labels:
        app: vigoda
        tier: web
    spec:
      containers:
      - name: vigoda
        image: windmill.build/millie/vigoda
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: vigoda
  labels:
    app: vigoda
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: vigoda
  selector:
    app: vigoda